GET http://localhost:5142/games

###
GET http://localhost:5142/games/4


###
POST http://localhost:5142/games
Content-Type: application/json

{
    "name": "Street",
    "genreId": 1,
    "price": 29.99,
    "releaseDate": "2001-11-18"
}

###
PUT http://localhost:5142/games/6
Content-Type: application/json

{
    "name": "Street Fighter VII",
    "genreId": 3,
    "price": 22.99,
    "releaseDate": "2012-10-21"
}

###
DELETE  http://localhost:5142/games/1


